name: ghw-build-deploy-app1-python

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
    
jobs:
  build:
    uses: yagami-escobar/workflows-compartidos/.github/workflows/build-docker.yaml@main # Aquí el 'main' es la rama del shared-workflowsss
    with:
      image-name: yagami-app
      dockerfile-path: ./Dockerfile
      registry-username: jhordan01 # El username ya no es secreto
    secrets:
      # Solo el token es secreto
      REGISTRY_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs: build # Depende del job de build
    uses: yagami-escobar/workflows-compartidos/.github/workflows/deploy-k8s.yaml@main
    with:
      deployment-name: yagami-app
      namespace: default
      image: ${{ needs.build.outputs.image-tag }} # El workflow reutilizable debe exponer este output
    # secrets:
    #   # Aquí pasas los secretos que el workflow reutilizable de deploy pueda necesitar (ej. KUBECONFIG)
    #   KUBECONFIG: ${{ secrets.KUBECONFIG }}